""

load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "stream",
    srcs = glob([ "src/**/*.h", "src/**/*.cpp" ]),
    hdrs = glob([ "src/**/*.h" ]),
    includes = [ "src/" ],
    copts = select({
        "@rules_cc//cc/compiler:msvc-cl": ["/std:latest"],
        "//conditions:default": ["-std=c++23"],
    }),
    strip_include_prefix = "src",
    include_prefix = "stream",
    linkstatic = True,
    visibility = ["//visibility:public"],
)

cc_test(
    name = "streamTests",
    srcs = glob([ "Tests/**/*.h", "Tests/**/*.cpp" ]),
    copts = select({
        "@rules_cc//cc/compiler:msvc-cl": ["/std:latest"],
        "//conditions:default": [
            "-std=c++23",
            "-Wall", "-Wextra", "-Wpedantic",
            "-Wshadow",
            "-Wconversion", "-Wsign-conversion",
            "-Werror=return-type"
        ],
    }),
    deps = [ ":stream" ],
    linkopts = select({
        "@rules_cc//cc/compiler:msvc-cl": [""],
        "//conditions:default": ["-pthread"],
    }),
    visibility = ["//visibility:public"],
)
