# Alternative GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug_x64
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

SHELLTYPE := posix
ifeq (.exe,$(findstring .exe,$(ComSpec)))
	SHELLTYPE := msdos
endif

# Configurations
# #############################################

RESCOMP = windres
INCLUDES += -Isrc -Isrc/EngineCore
FORCE_INCLUDE +=
ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
LIBS +=
LDDEPS +=
LINKCMD = $(AR) -rcs "$@" $(OBJECTS)
define PREBUILDCMDS
endef
define PRELINKCMDS
endef
define POSTBUILDCMDS
endef

ifeq ($(config),debug_x64)
TARGETDIR = ../bin/Linux-gmake2/Debug-x64/EngineCore
TARGET = $(TARGETDIR)/libEngineCore.a
OBJDIR = ../bin-int/Linux-gmake2/Debug-x64/EngineCore
DEFINES += -DARCHITECTURE_X64 -DTARGET_DEBUG -DCOMPILER_GMAKE -DPLATFORM_LINUX -DENGINECORE_BASE_LOGGER_NAME=\"EngineCore\"
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -O0 -g
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -O0 -g -std=c++20
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64

else ifeq ($(config),debug_x86)
TARGETDIR = ../bin/Linux-gmake2/Debug-x86/EngineCore
TARGET = $(TARGETDIR)/libEngineCore.a
OBJDIR = ../bin-int/Linux-gmake2/Debug-x86/EngineCore
DEFINES += -DARCHITECTURE_X86 -DTARGET_DEBUG -DCOMPILER_GMAKE -DPLATFORM_LINUX -DENGINECORE_BASE_LOGGER_NAME=\"EngineCore\"
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m32 -O0 -g
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m32 -O0 -g -std=c++20
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib32 -m32

else ifeq ($(config),release_x64)
TARGETDIR = ../bin/Linux-gmake2/Release-x64/EngineCore
TARGET = $(TARGETDIR)/libEngineCore.a
OBJDIR = ../bin-int/Linux-gmake2/Release-x64/EngineCore
DEFINES += -DARCHITECTURE_X64 -DTARGET_RELEASE -DCOMPILER_GMAKE -DPLATFORM_LINUX -DENGINECORE_BASE_LOGGER_NAME=\"EngineCore\"
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -O2 -g
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -O2 -g -std=c++20
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64

else ifeq ($(config),release_x86)
TARGETDIR = ../bin/Linux-gmake2/Release-x86/EngineCore
TARGET = $(TARGETDIR)/libEngineCore.a
OBJDIR = ../bin-int/Linux-gmake2/Release-x86/EngineCore
DEFINES += -DARCHITECTURE_X86 -DTARGET_RELEASE -DCOMPILER_GMAKE -DPLATFORM_LINUX -DENGINECORE_BASE_LOGGER_NAME=\"EngineCore\"
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m32 -O2 -g
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m32 -O2 -g -std=c++20
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib32 -m32

else ifeq ($(config),dist_x64)
TARGETDIR = ../bin/Linux-gmake2/Dist-x64/EngineCore
TARGET = $(TARGETDIR)/libEngineCore.a
OBJDIR = ../bin-int/Linux-gmake2/Dist-x64/EngineCore
DEFINES += -DARCHITECTURE_X64 -DTARGET_DIST -DCOMPILER_GMAKE -DPLATFORM_LINUX -DENGINECORE_BASE_LOGGER_NAME=\"EngineCore\"
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -O3
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -O3 -std=c++20
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -s

else ifeq ($(config),dist_x86)
TARGETDIR = ../bin/Linux-gmake2/Dist-x86/EngineCore
TARGET = $(TARGETDIR)/libEngineCore.a
OBJDIR = ../bin-int/Linux-gmake2/Dist-x86/EngineCore
DEFINES += -DARCHITECTURE_X86 -DTARGET_DIST -DCOMPILER_GMAKE -DPLATFORM_LINUX -DENGINECORE_BASE_LOGGER_NAME=\"EngineCore\"
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m32 -O3
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m32 -O3 -std=c++20
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib32 -m32 -s

endif

# Per File Configurations
# #############################################


# File sets
# #############################################

GENERATED :=
OBJECTS :=

GENERATED += $(OBJDIR)/FormatterHandler.o
GENERATED += $(OBJDIR)/JsonFactory.o
GENERATED += $(OBJDIR)/JsonObjects.o
GENERATED += $(OBJDIR)/JsonParser.o
GENERATED += $(OBJDIR)/ProfilerEventCreator.o
GENERATED += $(OBJDIR)/ProfilerFactory.o
GENERATED += $(OBJDIR)/TestSuite.o
OBJECTS += $(OBJDIR)/FormatterHandler.o
OBJECTS += $(OBJDIR)/JsonFactory.o
OBJECTS += $(OBJDIR)/JsonObjects.o
OBJECTS += $(OBJDIR)/JsonParser.o
OBJECTS += $(OBJDIR)/ProfilerEventCreator.o
OBJECTS += $(OBJDIR)/ProfilerFactory.o
OBJECTS += $(OBJDIR)/TestSuite.o

# Rules
# #############################################

all: $(TARGET)
	@:

$(TARGET): $(GENERATED) $(OBJECTS) $(LDDEPS) | $(TARGETDIR)
	$(PRELINKCMDS)
	@echo Linking EngineCore
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning EngineCore
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(GENERATED)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(GENERATED)) rmdir /s /q $(subst /,\\,$(GENERATED))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild: | $(OBJDIR)
	$(PREBUILDCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) | $(PCH_PLACEHOLDER)
$(GCH): $(PCH) | prebuild
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
$(PCH_PLACEHOLDER): $(GCH) | $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) touch "$@"
else
	$(SILENT) echo $null >> "$@"
endif
else
$(OBJECTS): | prebuild
endif


# File Rules
# #############################################

$(OBJDIR)/FormatterHandler.o: src/EngineCore/FMT/Detail/FormatterHandler/FormatterHandler.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ProfilerEventCreator.o: src/EngineCore/Instrumentation/ProfilerManger/ProfilerEventCreator.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ProfilerFactory.o: src/EngineCore/Instrumentation/ProfilerManger/ProfilerFactory.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/JsonFactory.o: src/EngineCore/Json/JsonFactory.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/JsonObjects.o: src/EngineCore/Json/JsonObjects.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/JsonParser.o: src/EngineCore/Json/JsonParser.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/TestSuite.o: src/EngineCore/Tester/TestSuite/TestSuite.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(PCH_PLACEHOLDER).d
endif