# Alternative GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug_x64
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

SHELLTYPE := posix
ifeq (.exe,$(findstring .exe,$(ComSpec)))
	SHELLTYPE := msdos
endif

# Configurations
# #############################################

RESCOMP = windres
INCLUDES += -Isrc -Isrc/EngineCore
FORCE_INCLUDE +=
ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
LINKCMD = $(CXX) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
define PREBUILDCMDS
endef
define PRELINKCMDS
endef
define POSTBUILDCMDS
endef

ifeq ($(config),debug_x64)
TARGETDIR = ../bin/Linux-gmake2/Debug-x64/EngineCoreTests
TARGET = $(TARGETDIR)/EngineCoreTests
OBJDIR = ../bin-int/Linux-gmake2/Debug-x64/EngineCoreTests
DEFINES += -DARCHITECTURE_X64 -DTARGET_DEBUG -DCOMPILER_GMAKE -DPLATFORM_LINUX
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -O0 -g
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -O0 -g -std=c++20
LIBS += ../bin/Linux-gmake2/Debug-x64/EngineCore/libEngineCore.a
LDDEPS += ../bin/Linux-gmake2/Debug-x64/EngineCore/libEngineCore.a
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64

else ifeq ($(config),debug_x86)
TARGETDIR = ../bin/Linux-gmake2/Debug-x86/EngineCoreTests
TARGET = $(TARGETDIR)/EngineCoreTests
OBJDIR = ../bin-int/Linux-gmake2/Debug-x86/EngineCoreTests
DEFINES += -DARCHITECTURE_X86 -DTARGET_DEBUG -DCOMPILER_GMAKE -DPLATFORM_LINUX
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m32 -O0 -g
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m32 -O0 -g -std=c++20
LIBS += ../bin/Linux-gmake2/Debug-x86/EngineCore/libEngineCore.a
LDDEPS += ../bin/Linux-gmake2/Debug-x86/EngineCore/libEngineCore.a
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib32 -m32

else ifeq ($(config),release_x64)
TARGETDIR = ../bin/Linux-gmake2/Release-x64/EngineCoreTests
TARGET = $(TARGETDIR)/EngineCoreTests
OBJDIR = ../bin-int/Linux-gmake2/Release-x64/EngineCoreTests
DEFINES += -DARCHITECTURE_X64 -DTARGET_RELEASE -DCOMPILER_GMAKE -DPLATFORM_LINUX
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -O2 -g
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -O2 -g -std=c++20
LIBS += ../bin/Linux-gmake2/Release-x64/EngineCore/libEngineCore.a
LDDEPS += ../bin/Linux-gmake2/Release-x64/EngineCore/libEngineCore.a
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64

else ifeq ($(config),release_x86)
TARGETDIR = ../bin/Linux-gmake2/Release-x86/EngineCoreTests
TARGET = $(TARGETDIR)/EngineCoreTests
OBJDIR = ../bin-int/Linux-gmake2/Release-x86/EngineCoreTests
DEFINES += -DARCHITECTURE_X86 -DTARGET_RELEASE -DCOMPILER_GMAKE -DPLATFORM_LINUX
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m32 -O2 -g
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m32 -O2 -g -std=c++20
LIBS += ../bin/Linux-gmake2/Release-x86/EngineCore/libEngineCore.a
LDDEPS += ../bin/Linux-gmake2/Release-x86/EngineCore/libEngineCore.a
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib32 -m32

else ifeq ($(config),dist_x64)
TARGETDIR = ../bin/Linux-gmake2/Dist-x64/EngineCoreTests
TARGET = $(TARGETDIR)/EngineCoreTests
OBJDIR = ../bin-int/Linux-gmake2/Dist-x64/EngineCoreTests
DEFINES += -DARCHITECTURE_X64 -DTARGET_DIST -DCOMPILER_GMAKE -DPLATFORM_LINUX
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -O3
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -O3 -std=c++20
LIBS += ../bin/Linux-gmake2/Dist-x64/EngineCore/libEngineCore.a
LDDEPS += ../bin/Linux-gmake2/Dist-x64/EngineCore/libEngineCore.a
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -s

else ifeq ($(config),dist_x86)
TARGETDIR = ../bin/Linux-gmake2/Dist-x86/EngineCoreTests
TARGET = $(TARGETDIR)/EngineCoreTests
OBJDIR = ../bin-int/Linux-gmake2/Dist-x86/EngineCoreTests
DEFINES += -DARCHITECTURE_X86 -DTARGET_DIST -DCOMPILER_GMAKE -DPLATFORM_LINUX
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m32 -O3
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m32 -O3 -std=c++20
LIBS += ../bin/Linux-gmake2/Dist-x86/EngineCore/libEngineCore.a
LDDEPS += ../bin/Linux-gmake2/Dist-x86/EngineCore/libEngineCore.a
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib32 -m32 -s

endif

# Per File Configurations
# #############################################


# File sets
# #############################################

GENERATED :=
OBJECTS :=

GENERATED += $(OBJDIR)/BaseTypes.o
GENERATED += $(OBJDIR)/Index.o
GENERATED += $(OBJDIR)/Shift.o
GENERATED += $(OBJDIR)/Specifiers.o
GENERATED += $(OBJDIR)/Tests.o
GENERATED += $(OBJDIR)/TextProperties.o
OBJECTS += $(OBJDIR)/BaseTypes.o
OBJECTS += $(OBJDIR)/Index.o
OBJECTS += $(OBJDIR)/Shift.o
OBJECTS += $(OBJDIR)/Specifiers.o
OBJECTS += $(OBJDIR)/Tests.o
OBJECTS += $(OBJDIR)/TextProperties.o

# Rules
# #############################################

all: $(TARGET)
	@:

$(TARGET): $(GENERATED) $(OBJECTS) $(LDDEPS) | $(TARGETDIR)
	$(PRELINKCMDS)
	@echo Linking EngineCoreTests
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning EngineCoreTests
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(GENERATED)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(GENERATED)) rmdir /s /q $(subst /,\\,$(GENERATED))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild: | $(OBJDIR)
	$(PREBUILDCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) | $(PCH_PLACEHOLDER)
$(GCH): $(PCH) | prebuild
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
$(PCH_PLACEHOLDER): $(GCH) | $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) touch "$@"
else
	$(SILENT) echo $null >> "$@"
endif
else
$(OBJECTS): | prebuild
endif


# File Rules
# #############################################

$(OBJDIR)/BaseTypes.o: Tests/FMT/BaseTypes.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Index.o: Tests/FMT/Index.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Shift.o: Tests/FMT/Shift.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Specifiers.o: Tests/FMT/Specifiers.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/TextProperties.o: Tests/FMT/TextProperties.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Tests.o: Tests/Tests.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(PCH_PLACEHOLDER).d
endif