""

# buildifier: disable=module-docstring
module(
    name = "streamformat",
    version = "0.1",
)

git_override(module_name="bazel_utilities", remote="https://github.com/0-Sacha/bazel_utilities.git", commit="7f6c3585c41278918428ed48d45b12413c197fc0")
git_override(module_name="bazel_buildbuddy", remote="https://github.com/0-Sacha/bazel_buildbuddy.git", commit="65259b523c8cd5c0c1698114c948a6cff33ddb92")
git_override(module_name="bazel_winlibs", remote="https://github.com/0-Sacha/bazel_winlibs.git", commit="05f805d85dd5a4c1fa5bcab6244e6ad01d2ce737")

bazel_dep(name = "rules_cc", version = "0.0.10")
bazel_dep(name = "platforms", version = "0.0.10")
bazel_dep(name = "bazel_utilities", version = "0.0.1")
bazel_dep(name = "bazel_buildbuddy", version = "0.0.1")
bazel_dep(name = "bazel_winlibs", version = "0.0.1")

bazel_dep(name = "hedron_compile_commands", dev_dependency = True)
git_override(
    module_name = "hedron_compile_commands",
    remote = "https://github.com/hedronvision/bazel-compile-commands-extractor.git",
    commit = "1e08f8e0507b6b6b1f4416a9a22cf5c28beaba93",
)

winlibs_toolchain_extension = use_extension("@bazel_winlibs//:rules.bzl", "winlibs_toolchain_extension")
inject_repo(winlibs_toolchain_extension, "platforms", "bazel_utilities")
winlibs_toolchain_extension.winlibs_toolchain(name = "winlibs")
winlibs_toolchain_extension.winlibs_toolchain(name = "pthread-winlibs", linklibs = [ "pthread" ])
use_repo(winlibs_toolchain_extension, "winlibs")
use_repo(winlibs_toolchain_extension, "pthread-winlibs")
# register_toolchains("@winlibs//:clang-toolchain")

buildbuddy_toolchain_extension = use_extension("@bazel_winlibs//:rules.bzl", "buildbuddy_toolchain_extension")
inject_repo(buildbuddy_toolchain_extension, "platforms", "bazel_utilities")
buildbuddy_toolchain_extension.winlibs_toolchain(name = "winlibs")
use_repo(buildbuddy_toolchain_extension, "buildbuddy")
# register_toolchains("@buildbuddy//:gcc-toolchain")
