""

load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "units",
    srcs = [ "tests.cpp" ] + glob([ "fmt/*.h", "fmt/*.cpp" ]),
    copts = select({
        "@rules_cc//cc/compiler:msvc-cl": ["/std:latest"],
        "//conditions:default": [
            "-std=c++23",
            "-Wall", "-Wextra", "-Wpedantic",
            "-Wshadow",
            "-Wconversion", "-Wsign-conversion",
            "-Werror=return-type"
        ],
    }),
    deps = [ "//:stream" ],
    linkopts = select({
        "@rules_cc//cc/compiler:msvc-cl": [""],
        "//conditions:default": ["-pthread"],
    }),
    visibility = ["//visibility:public"],
)
