agents:
  queue: "agent-runners-linux-amd64"

steps:
  - label: ":bazel: Build and Test on gcc (W asan)"
    commands:
      - CC=gcc bazelisk build --features=asan //...
      - CC=gcc bazelisk test --features=asan //...

  - label: ":bazel: Build and Test on Clang (W asan)"
    commands:
      - CC=clang bazelisk build --features=asan //...
      - CC=clang bazelisk test --features=asan //...
