agents:
  queue: "agent-runners-linux-amd64"

steps:
  - label: ":bazel: Build and Test on gcc (W asan)"
    commands:
      - CC=gcc-14 bazelisk build --features=asan //:streamTests
      - CC=gcc-14 bazelisk test --features=asan //:streamTests

  - label: ":bazel: Build and Test on Clang (W asan)"
    commands:
      - CC=clang-20 bazelisk build --features=asan //:streamTests
      - CC=clang-20 bazelisk test --features=asan //:streamTests
