agents:
  queue: "agent-runners-linux-amd64"

steps:
  - label: ":bazel: Build and Test on gcc (W asan)"
    commands:
      - CC=gcc bazelisk build --features=asan //tests:units
      - CC=gcc bazelisk test --features=asan //tests:units

  - label: ":bazel: Build and Test on Clang (W asan)"
    commands:
      - CC=clang-20 bazelisk build --features=asan //tests:units
      - CC=clang-20 bazelisk test --features=asan //tests:units
