agents:
  queue: "agent-runners-windows-amd64"

steps:
  - label: ":bazel: Build And Test Winlibs/clang"
    commands:
      - bazelisk build --config=winlibs-clang //tests:units
  - label: ":bazel: Build And Test Winlibs/gcc"
    commands:
      - bazelisk build --config=winlibs-gcc //tests:units
