load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "bazel_utilities",
    strip_prefix = "bazel_utilities-7c379bd1b6a4ae0ff5123b63385f92fb527bd687",
    urls = [ "https://github.com/0-Sacha/bazel_utilities/archive/7c379bd1b6a4ae0ff5123b63385f92fb527bd687.zip" ],
    integrity = "sha256-L5hWrjLMFOdplqV6X0xCyvINMjhnQHSTXynUYZNm9Qs="
)

http_archive(
    name = "bazel_winlibs_mingw",
    strip_prefix = "bazel_winlibs_mingw-09c1b538db4fa262bba152b24b7c1d61079e5abe",
    urls = [ "https://github.com/0-Sacha/bazel_winlibs_mingw/archive/09c1b538db4fa262bba152b24b7c1d61079e5abe.zip" ],
    integrity = "sha256-rxd9695aR8gQ7sOFiz1YUDURvdgqi+3o3GLygEVLuas="
)

load("@bazel_winlibs_mingw//:rules.bzl", "winlibs_mingw_toolchain")
# winlibs_mingw_toolchain(
#     "mingw",
#     copts = [ "-g", "-O0" ],
# )
