name: stream

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  # windows-latest-msvc:
  #   runs-on: windows-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #   - uses: bazelbuild/setup-bazelisk@v3
  #   - name: Mount bazel cache
  #     uses: actions/cache@v4
  #     with:
  #       path: "~/.cache/bazel"
  #       key: bazel
  #   - name: Building...
  #     run: bazelisk build //:streamTests
  #   - name: Testing...
  #     run: bazelisk test //:streamTests
      
  windows-latest-winlibs:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: bazelbuild/setup-bazelisk@v3
    - name: Mount bazel cache
      uses: actions/cache@v4
      with:
        path: "~/.cache/bazel"
        key: bazel
    - name: Build Winlibs/clang...
      run: bazelisk build --config=winlibs-clang //:streamTests
    - name: Build Winlibs/gcc...
      run: bazelisk build --config=winlibs-gcc //:streamTests

  ubuntu-latest-gcc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: bazelbuild/setup-bazelisk@v3
    - name: Mount bazel cache
      uses: actions/cache@v4
      with:
        path: "~/.cache/bazel"
        key: bazel
    - name: Install Gcc 13
      run: |
        sudo apt install software-properties-common
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt install gcc-13
    - name: Version
      run: gcc --version
    - name: Version
      run: gcc-13 --version
    - name: Building...
      run: CC=gcc-13 bazelisk build //:streamTests
    - name: Testing... (W asan)
      run: CC=gcc-13 bazelisk test --features=asan //:streamTests

  ubuntu-latest-clang:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: bazelbuild/setup-bazelisk@v3
    - name: Mount bazel cache
      uses: actions/cache@v4
      with:
        path: "~/.cache/bazel"
        key: bazel
    - name: Install clang 20
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x ./llvm.sh
        sudo ./llvm.sh 20
    - name: Version
      run: clang++-20 --version
    - name: Building...
      run: CC=clang++-20 bazelisk build //:streamTests
    - name: Testing... (W asan)
      run: CC=clang++-20 bazelisk test --features=asan //:streamTests
