name: Tests Linux

on:
  push:
    branches:
      - '**'

jobs:
  ubuntu-latest-gcc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: bazelbuild/setup-bazelisk@v3
    - uses: actions/cache@v4
      with:
        path: "~/.cache/bazel"
        key: bazel
    - name: Version
      run: gcc --version
    - name: Building...
      run: CC=gcc bazelisk build //tests:units
    - name: Testing (asan)...
      run: CC=gcc bazelisk test //tests:units
    - name: Testing (asan)...
      run: CC=gcc bazelisk test --features=asan //tests:units

  ubuntu-latest-clang:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: bazelbuild/setup-bazelisk@v3
    - uses: actions/cache@v4
      with:
        path: "~/.cache/bazel"
        key: bazel
    - name: Install clang
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x ./llvm.sh
        sudo ./llvm.sh 17
    - name: Version
      run: clang --version
    - name: Building...
      run: CC=clang++-17 bazelisk build //tests:units
    - name: Testing...
      run: CC=clang++-17 bazelisk test //tests:units
    - name: Testing (asan)...
      run: CC=clang++-17 bazelisk test --features=asan //tests:units
